### ISSUE TITLE
Sample Code to Upload Attachments

### ISSUE THREAD

**Issue by Acidrai0** [zoho/zohocrm-python-sdk-7.0#10]
Can you please add some sample code to upload attachments to a record

**Comment by raja-k-7453** [comment]
Hi @Acidrai0 , We have updated the sample code. Please refer this [link](https://github.com/zoho/zohocrm-python-sdk-7.0/tree/master/samples/attachments) for the details.

**Comment by Acidrai0** [comment]
Thanks a lot for your swift response
