### ISSUE TITLE
How to download field attachments?

### ISSUE THREAD

**Issue by Acidrai0** [zoho/zohocrm-python-sdk-7.0#6]
I didn't find any samples on how can I download field attachments

**Comment by raja-k-7453** [comment]
Hi @Acidrai0 , We have updated the sample code. Please refer this [link](https://github.com/zoho/zohocrm-python-sdk-7.0/blob/master/samples/field_attachments/GetFieldAttachments.py) for the details.

**Comment by Acidrai0** [comment]
Thanks a lot
